name: Incident report - Form
description: Report an incident with potential or lasting impact on a product or service
title: ":question: is unavailable since :question:"
labels: ["incident"]
body:
- id: header
  type: markdown
  attributes:
    value: |
      ## Give a proper title above :arrow_up_small:
      ## Fill the following fields :arrow_down_small:
- id: description
  type: textarea
  attributes:
    label: Description
    description: |
      Describe in a few words what has been detected
      Please refer to the relevant [product](https://docs.latfa.net/engineering/latest/products/readme.html) or [service](https://docs.latfa.net/it-ops/latest/services/readme.html) if possible
    placeholder: |
      Service ... is not available and display this error message
       or
      Secret ... have been found on ... where they should not be
       or
      Data ... have been transfert to ... but seem to be corrupted
  validations:
    required: true
- id: detector
  type: input
  attributes:
    label: Detector
    description: Who or what has detected this for the first time?
    placeholder: "monitoring.example.com, email@example.com, @la-test/sbx"
  validations:
    required: true
- id: detection_time
  type: input
  attributes:
    label: Detection time
    description: When was this detected for the first time?
    placeholder: "YYYY/MM/DD HH:MM UTC"
  validations:
    required: true
- id: reporting_time
  type: input
  attributes:
    label: Reporting time
    description: When was this reported first elsewhere, if not here now?
    placeholder: "YYYY/MM/DD HH:MM UTC"
  validations:
    required: false
- id: last_time
  type: input
  attributes:
    label: Last time
    description: When was the last time that the observed effects were NOT yet visible, if relevant?
    placeholder: "YYYY/MM/DD HH:MM UTC"
  validations:
    required: false
- id: classification
  type: dropdown
  attributes:
    label: Classification
    description: Select the tag(s) classifying this incident
    multiple: true
    options:
      - Unknown/Todo later
      - Showstopper
      - Availability
      - Confidentiality
      - Integrity
      - Permanent
      - Intermittent
      - Already resolved
  validations:
    required: true
- id: location
  type: dropdown
  attributes:
    label: Location
    description: Where did this happened?
    multiple: true
    options:
      - Unknown/Todo later
      - Third-party datacenter
      - Berlin headquarter
      - Remote workplace
  validations:
    required: true
- id: other_parties
  type: textarea
  attributes:
    label: Other parties
    description: Describe who else has been involved in this incident and when
    placeholder: |
      Alice has reported this first in the chat earlier today at HH:MM UTC.
      Bob helped me filling up this issue
      Charlie has been informed and will notified the client by email later today
  validations:
    required: false
- id: mention_team
  type: input
  attributes:
    label: Mention team
    description: Only change to mention an other team
    value: "@la-test/sbx"
  validations:
    required: true
- id: footer
  type: markdown
  attributes:
    value: |
      ## Remember those answers can always be changed later :arrow_forward:
