name: "Onboarding or Offboarding - Form"
description: "Request support for the onboarding or offboarding of a team member (using a form)"
title: "[Onboarding or Offboarding]: <... as ... member>"
labels: ["access"]
body:
- id: above
  type: markdown
  attributes:
    value: "### Fill the field above with a proper title"
- id: common
  type: markdown
  attributes:
    value: "### Fill the following fields for any team member"
- id: name
  type: input
  attributes:
    label: First name and surname or alias
    placeholder: John Doe
  validations:
    required: true
- id: favorite_username
  type: input
  attributes:
    label: Favorite username
    description: To be used when possible
    placeholder: jdoe
  validations:
    required: false
- id: github_username
  type: input
  attributes:
    label: Existing Github username
    description: To access the relevant repositories
    placeholder: johndoe123
  validations:
    required: true
- id: email
  type: input
  attributes:
    label: Least Authority email address
    placeholder: john@leastauthority.com
  validations:
    required: true
- id: ps_email
  type: input
  attributes:
    label: Private Storage email address
    description: Only for Private Storage team members
    placeholder: john@private.storage
  validations:
    required: false
- id: devops
  type: markdown
  attributes:
    value: "### Fill the following fields only for Dev/Ops team member"
- id: ssh_key
  type: textarea
  attributes:
    label: SSH public key
    description: To access the systems
    placeholder: |
      ssh-rsa/ed25519/... ... john@leastauthority.com
  validations:
    required: false
- id: gpg_key
  type: textarea
  attributes:
    label: GPG public key
    description: To decrypt the secrets
    placeholder: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      ...
      -----END PGP PUBLIC KEY BLOCK-----
  validations:
    required: false
- id: mention_team
  type: input
  attributes:
    label: Mention team
    description: Only to mention an other team
    value: "@la-test/sbx"
  validations:
    required: true
