name: "Onboarding or Offboarding - Form"
description: "Request support for the onboarding or offboarding of a team member (using a form)"
title: "[Onboarding or Offboarding]: <... as ... member>"
labels: ["access"]
body:
- id: common
  type: markdown
  attributes:
    value: |
      ## Give a proper title above :arrow_up_small:
      ## Fill the following fields :arrow_down_small:
- id: name
  type: input
  attributes:
    label: First name and surname or alias
    placeholder: John Doe
  validations:
    required: true
- id: email
  type: input
  attributes:
    label: Least Authority email address
    placeholder: john@leastauthority.com
  validations:
    required: true
- id: ps_email
  type: input
  attributes:
    label: Private Storage email address
    description: Only for Private Storage team members
    placeholder: john@private.storage
  validations:
    required: false
- id: prefered_username
  type: input
  attributes:
    label: Prefered username
    description: Only to be used where possible
    placeholder: jdoe
  validations:
    required: false
- id: github_username
  type: input
  attributes:
    label: Existing Github username
    description: Only to access repositories
    placeholder: johndoe123
  validations:
    required: false
- id: ssh_key
  type: textarea
  attributes:
    label: SSH public key
    description: Only to access the systems
    placeholder: |
      ssh-rsa/ed25519/... ... john@leastauthority.com
  validations:
    required: false
- id: gpg_key
  type: textarea
  attributes:
    label: GPG public key
    description: Only to decrypt the secrets
    placeholder: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      ...
      -----END PGP PUBLIC KEY BLOCK-----
  validations:
    required: false
- id: mention_team
  type: input
  attributes:
    label: Mention team
    description: Only change to mention an other team
    value: "@la-test/sbx"
  validations:
    required: true
